### ISSUE TITLE
Add legend, hide Total and change sentinel words

### ISSUE THREAD

**Issue by perezcotai** [nishantjainuk/SimpleWaterfall-PowerBI#11]
Hi there,
Is possible to add legend, hide the total and have the option to change sentinel words from chart? 

your custom viz work great... thanks for you effort.

**Comment by nishantjainuk** [comment]
Hi @perezcotai 

Could you please explain a bit more about your suggestions. 

Legend: There isn't usual a legend in waterfall chart. The only information that you can display is what each of the sentiment colors mean i.e. great = positive, red = negative etc. There aren't any other colors available to show in the legent. 

Hide totals: Can you be more specific what you mean by hiding totals?

Change sentiment words: Again, sentiment (i.e. Total, increase and decrease) these are not show in the chart at the moment. Is that what you mean by legend?

Please provide screenshots if possible of what you would like to see. 

Again, thanks for your feedback and would appreciate if you could leave a feedback on the [appsource](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200000195)

**Comment by perezcotai** [comment]
The idea that I have in mind with the **legend.**
 For example:
If the measure has “**Low value is good** “. 
The decrease of the Metric A(Contributors)Green negative value
The increase of the Metric A(Detractors) RED   positive value
![image](https://user-images.githubusercontent.com/28602856/78510262-a0b17300-7759-11ea-84c1-0b6c787ef415.png)
![image](https://user-images.githubusercontent.com/28602856/78510276-b4f57000-7759-11ea-891d-64154c7f7077.png)


But if the measure now has “**High value is good”**. 
The  increase of the Metric S(Contributor) Red  positive value
The decrease of the Metric S(Detractors) Green negative value
![image](https://user-images.githubusercontent.com/28602856/78510286-c0e13200-7759-11ea-98d4-9cadcaa89315.png)
![image](https://user-images.githubusercontent.com/28602856/78510288-c3dc2280-7759-11ea-8ee5-03487947b4a3.png)


For the **sentiment words** have the opportunity to show
**Low value is good.**
Decrease show the word Contributor
Increase show the word Detractor
**High value is good.**
Increase show the word Detractor
Decrease show the word Contributor

Then for **total** get the option to show or not show it in the chart.

**Comment by nishantjainuk** [comment]
Got it. It's a good suggestion. Let me get this up and running. Would you be interested in testing this version before it is published by Microsoft for general availability. 

Thanks 
Nishant

**Comment by perezcotai** [comment]
Absolutely I am glad to help test it as many time is need it.

**Comment by nishantjainuk** [comment]
@perezcotai 

I hope you are doing well. I have updated the custom visual to include your suggestion. I have submitted this to Microsoft however it will take about 4 weeks for it to go live on appsource. 

In the mean time, you can download the beta version of the visual from [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/master/Beta%20Version/SimpleWaterfall_dev.2.0.10.0.pbiviz?raw=true)

The new features available are:

1. Legend: The legend is now available. By default, it is switched off but you can switch it on from the properties pane. You can also change the "text" to be used for favourable and adverse sentiment
2. You can now remove the "Total" bar by switching off the "Show cumulative total" option in the "Define Pillar" section. 

I would appreciate if you could test and provide your feedback on these features. 

Nishant

**Comment by perezcotai** [comment]
Let me do the test.. :)

**Comment by perezcotai** [comment]
The two new features work perfect :).
But "fit to width" for the chart  alias  FitToWidth stop to work and the decimals numbers from the format stop to work. 
![image](https://user-images.githubusercontent.com/28602856/80387300-1a76e100-886e-11ea-9602-2ca28a0dd1b0.png)

**Comment by nishantjainuk** [comment]
@perezcotai 

I have updated the visual. Can you download it again from this [link ](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/master/Beta%20Version/SimpleWaterfall_dev.2.0.10.0.pbiviz?raw=true) and test it. Appreciate your support with testing

Thanks
Nishant

**Comment by perezcotai** [comment]
Sure

**Comment by perezcotai** [comment]
Now, work perfect ... FitToWidth   and the decimals numbers from the format are working.

**Comment by perezcotai** [comment]
Review all the FitToWidth for the vertical  Chart Option is also not working anymore

**Comment by perezcotai** [comment]
let me know if you need help for test

**Comment by nishantjainuk** [comment]
Thanks

The latest version is available here

https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/master/Beta%20Version/SimpleWaterfall_dev.2.0.10.2.pbiviz?raw=true

Let mr know if you find any issues


Thanks
Nishant

On 13 May 2020 at 16:33, perezcotai <notifications@github.com<mailto:notifications@github.com>> wrote:


let me know if you need help for test

**Comment by perezcotai** [comment]
The "fit to width" work only with horizontal chart but fail with vertical chart.
Then,  I get extra decimals numbers as you see in the bellow chart. 

![image](https://user-images.githubusercontent.com/28602856/81876818-2d193780-9549-11ea-9fc8-d76ef5208413.png)
 

 
![image](https://user-images.githubusercontent.com/28602856/81876905-62be2080-9549-11ea-9b98-7332521c949b.png)

**Comment by perezcotai** [comment]
Let me know if you need help to test

**Comment by nishantjainuk** [comment]
@perezcotai 

I fixed a lot of issues when I released the last version in May earlier this year.  But I am not sure if I have fixed all the issues you suggested. I am closing this issue as it is quite old but can you create new issues if you still have any left. 

I have got some time now to continue my work on this visual and would be glad to fix some of your issues. 

Looking forward for more issues from you.
