### ISSUE TITLE
Get visual certified

### ISSUE THREAD

**Issue by Mike-Honey** [nishantjainuk/SimpleWaterfall-PowerBI#12]
Great work on this visual - it's my pick of the bunch of waterfalls currently available.

Can you get it certified by Microsoft?  That would let the users export to PowerPoint etc.

Thanks!

**Comment by nishantjainuk** [comment]
Thanks Mike. I have already submitted it for certification with Microsoft. There is a long lead time so not sure how long it will take. I am eagerly waiting to hear from them

Thanks
Nishant

**Comment by Mike-Honey** [comment]
Great - thanks for your efforts on this.

**Comment by nishantjainuk** [comment]
@Mike-Honey Good news. The visual is certified.
