### ISSUE TITLE
X-Axis formatting incorrect 

### ISSUE THREAD

**Issue by nishantjainuk** [nishantjainuk/SimpleWaterfall-PowerBI#13]
The visual doesn't respect field formatting of date from SSAS. In SSAS I have this formatting for date field: MMMM yyyy but in the visual I see yyyy-mm-ddThh:mm:ss
![waterafall_vs_barchart](https://user-images.githubusercontent.com/24504997/79910101-fd798280-8415-11ea-90b8-123e8666f41f.PNG)

**Comment by ZdenekSoldan** [comment]
Hi Nishant,

I tried your workaround with formating the date as text using DAX FORMAT and it works but I calculate monthly differences using DAX PREVIOUSMONTH and it needs date format. So the calculation doesn't work. 
Thank you very much.

**Comment by nishantjainuk** [comment]
@ZdenekSoldan 

One option is that you create 2 measures exactly the same and use of them with the format function and in the visual and another one for the PREVIOUSMONTH calculation. 

Nishant

**Comment by nishantjainuk** [comment]
Hi @ZdenekSoldan 

I hope you are doing well. I have updated the custom visual to fix this bug. I have submitted this to Microsoft however it will take about 4 weeks for it to go live on appsource. 

In the mean time, you can download the beta version of the visual from [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/master/Beta%20Version/SimpleWaterfall_dev.2.0.10.0.pbiviz?raw=true)

As I don't have the option to test it against SSAS, I would really appreciate if you could test and provide your feedback on this bug. 

Nishant

**Comment by ZdenekSoldan** [comment]
Hi Nishant,

it works great! Thank you very much. But I also registered a new problem with labels which haven't been problematic in the old version. Now when you have selected automatic selection of label's units it looks like it takes unit from the first bar and propagated it to all others. In my case, the first bar is commonly in millions but changes could be in thousands and it shows 0M.

Thank you very much for you time and improvements!
Best regards,

Zdenek

**Comment by nishantjainuk** [comment]
@ZdenekSoldan 

Hi there, 

I have updated the visual. You can download it [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/master/Beta%20Version/SimpleWaterfall_dev.2.0.10.0.pbiviz?raw=true). Can you try again please and let me know if this has worked or not?

Thanks
Nishant

**Comment by ZdenekSoldan** [comment]
Hi Nishant,

now it works perfectly fine!
Thank you very much.

Zdenek

**Comment by nishantjainuk** [comment]
@ZdenekSoldan Closing this bug as this issue is fixed in version 2.10.0.1 .
