### ISSUE TITLE
Option to hide final pillar 

### ISSUE THREAD

**Issue by nishantjainuk** [nishantjainuk/SimpleWaterfall-PowerBI#14]
Would it be possible to not show the final pillar at all? 

![waterafall_vs_barchart](https://user-images.githubusercontent.com/24504997/79910191-2863d680-8416-11ea-9ae9-584b4f8a1b4a.PNG)

**Comment by nishantjainuk** [comment]
@ZdenekSoldan

I add this additional issue on your behalf. 

You can now remove the "Total" bar by switching off the "Show cumulative total" option in the "Define Pillar" section.

I would appreciate if you could test and provide your feedback on these features.

Nishant

**Comment by ZdenekSoldan** [comment]
Hi Nishant,

it works great!
Thank you very much.

Best regards,
Zdenek

**Comment by nishantjainuk** [comment]
@ZdenekSoldan The latest version has been released by Microsoft. Let me know if you have any questions.
