### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by nishantjainuk** [nishantjainuk/SimpleWaterfall-PowerBI#16]
Would you be able to add a sort order by value? Currently I can only sort values by alphabetically by category

![Capture](https://user-images.githubusercontent.com/24504997/79911266-ff444580-8417-11ea-9bbd-03b4a5581b43.PNG)

**Comment by nishantjainuk** [comment]
Requested by Andrew Wong

**Comment by nishantjainuk** [comment]
Visual now including option to sort sub-pillars

You can change the sorting from the “Chart Options” section. You have 3 options


1.	Default – users the internal model’s sort option
2.	Ascending – positive first
3.	Descending – negative first

**Comment by slvaman69** [comment]
Hi Nishant,

Thanks for this functionality that I have been able to test with the dev version of your visual.
I have an additional question on this topic.

Are you planning to allow sorting for another value than the category or the value?
For instance, with the default PowerBI Waterfall Chart, you can add a field in the "Tooltips" section:
![Waterfall chart order 1](https://user-images.githubusercontent.com/33895905/80795150-fc75ed00-8b9b-11ea-8811-285ae3da2e77.jpg)

And then you are able to use the default internal model's sort option to sort by this new field:
![Waterfall chart order 2](https://user-images.githubusercontent.com/33895905/80795176-10215380-8b9c-11ea-964e-52944950e711.jpg)

Thanks a lot for your help and don't hesitate if you need additional information.

**Comment by nishantjainuk** [comment]
@slvaman69 Microsoft have released the updated version which has the new sort capability. You can now replace the dev version with the official version if you are using it. 

Regarding the use of additional fields to sort the data, it should be possible once I add the tooltip option.  I will add it in the next release. 

Thanks again for your feedback and support. Keep them comiing.

Nishant
