### ISSUE TITLE
Wrong visualization of correct measure on the start of the year

### ISSUE THREAD

**Issue by ZdenekSoldan** [nishantjainuk/SimpleWaterfall-PowerBI#18]
Hello Nishant,
I found a strange behaviour with slicer selection and the SimpleWaterfall. 
I have two situations which should give the same result but they don't. I have a Year slicer in my report. The slicer shows only the relevant record of date dimension (filter on COUNTROWS > 1). When I choose to select all from the slicer, SimpleWaterfall shows correct value for Volume_diff measure on the start of the second year (Year_selectAll.png). But when I choose to select all available months with ctrl + clicking on each month, the value for Volume_diff measure is wrong on the start of the second year (Year_selection.png). Volume_diff is calculated as SUM(Volume) - CALCULATE(SUM(Volume),PREVIOUSMONTH(yearmonth column)).

Year_selectAll.png
![Year_selectAll](https://user-images.githubusercontent.com/26428515/80095088-a97eb300-8567-11ea-8c48-570c49aca134.png)

Year_selection.png
![Year_selection](https://user-images.githubusercontent.com/26428515/80095142-c0bda080-8567-11ea-93c1-1b8fa06d2ec9.png)

**Comment by nishantjainuk** [comment]
Hi, 

The simple waterfall doesn't do any calculation of its own. It simply relies on the numbers provided by the measures. In this case, I believe it has to do the measure. Click on the "..." on the top right of the visual and select "Show Data". Can you check if the table is showing you the correct information?

Thanks
Nishant

**Comment by ZdenekSoldan** [comment]
The table after Show Data is showing the wrong information. But when I put the same measure on the bar chart with the same x axis it shows the correct information. Also in the table on the print screens, the information is correct. Only SimpleWaterfall is showing the wrong one.
![comparison](https://user-images.githubusercontent.com/26428515/80096595-20b54680-856a-11ea-9fa8-631a1bfcb03d.PNG)

**Comment by nishantjainuk** [comment]
The way the custom visual works, it relies on the data sent by the model. Simple waterfall will show you what is displayed on the "Show Data" section. "Show Data" come from the model. You will have to investigate at your end because there isn't anything I can do. 

I would suggest you create a new table with exactly the same fields you are using in the simple waterfall. Hopefully that will help you to investigate the issue. 

Let me know how it goes

Thanks
Nishant

**Comment by nishantjainuk** [comment]
@ZdenekSoldan 

Just checking if you managed to find the issue. If not, would it be possible for you to send me the pbix file. Make sure you don't include any sensitive data

Thanks

**Comment by ZdenekSoldan** [comment]
Hi Nishant,

I found the problem. You were right. The problem is not in the visual. I use Countrows >= 1 Filter in the visual to show only relevant months and this is causing the problem but I don't know why.

Thanks a lot,
Zdenek
