### ISSUE TITLE
"Value decimal places" for Labels

### ISSUE THREAD

**Issue by slvaman69** [nishantjainuk/SimpleWaterfall-PowerBI#20]
Dear Nishant,

Thanks a lot for your visual that is very helpful and looking amazing.
I was wondering if you were planning to enhance it so that the number of digits for the values can be defined?

Indeed, in the "Labels" section, it is possible to define the "Value Format" (Billions, Millions...) but not the "Value decimal places" (as it exists in most of the default PowerBi visuals).
For instance I would like my values to appears as such "48.67bn" whereas today it shows "49bn".
Unless I missed something, the only other option that I think I have is to show millions "48672M" which is not really looking friendly.

Thanks in advance for your help and all your work.

**Comment by nishantjainuk** [comment]
@slvaman69 Thanks for your support The latest version has the capability for you to add decimal places. Please let me know if you have any further questions or issues
