### ISSUE TITLE
Hiding total bars between the changes

### ISSUE THREAD

**Issue by laky27** [nishantjainuk/SimpleWaterfall-PowerBI#28]
Hi there, love your visual!

So i typically don't use your visual with anything in the category, but I recently had to because I'm comparing 2 different time periods and the Date field needed to be added in order for values to show up. When that happens I get what I want, but the inner total bars aren't really needed, I just need the starting/ending total, and then the differences between the measure's I've brought in?

Any way to hide the 3 middle total bars?
![image](https://user-images.githubusercontent.com/61324675/82506345-22205300-9ac5-11ea-8f4d-e7412480d738.png)

Thanks again for the great visual!

**Comment by nishantjainuk** [comment]
@laky27 , 

Can you send me a screenshot of how the visualisation pane looks like? 

The only way you can have multiple pillars is either

- by defining them in the "Define Pillars" section
- or you have 2 or more measure and 2 or more categories. 
- or you have 2 or more measure and 1 category. 

Can you remove multiple measures or categories if you have them. I think for what you need, you need 1 category and 2 measures. Each measure will become a pillar (one at start and one at the end) with categories coming in the middle. 

Thanks
Nishant

**Comment by nishantjainuk** [comment]
@laky27 Is this still an issue? if so, can you send me the screenshot I requested earlier.

**Comment by nishantjainuk** [comment]
Closing as haven't received a response to my earlier query. If this is still an issue, please open a new issue and attached a screenshot explaining the issue and I will be happen to look into it
