### ISSUE TITLE
Horizontal line on y=0

### ISSUE THREAD

**Issue by mldrs** [nishantjainuk/SimpleWaterfall-PowerBI#29]
Hey there,

I'm currently exploring the features of your waterfall and I love the way it works and looks!

One small question: would it be possible to add the option to insert a horizontal line on a specific y axis value? Let me show you why I ask:

If values are all positive, the graph looks perfect. It's clear that (sub)total bars are (sub)total bars because they start at the bottom of the graph:

![afbeelding](https://user-images.githubusercontent.com/64649754/83276719-5684c500-a1d1-11ea-8204-24a67d945ccc.png)

However, when categories turn negative, the (sub)total bars seem to be "floating" a bit because it's not very clear where the 0 line is:

![afbeelding](https://user-images.githubusercontent.com/64649754/83276776-6b615880-a1d1-11ea-89ec-e9c06410c82f.png)

What I would like is to have an option to have a horizontal line at a specific y axis value (or just at zero), which would look something like this:

![afbeelding](https://user-images.githubusercontent.com/64649754/83276935-9fd51480-a1d1-11ea-8ba7-003c8cfd3a94.png)

(but perhaps behind the bars instead of overlapping).

Do you think that would be possible?

Thanks in advance!

**Comment by nishantjainuk** [comment]
Thanks @mldrs. This is really a good suggestion. I will add this in my next version update. I will keep you posted how it goes.

**Comment by mldrs** [comment]
Awesome to hear @nishantjainuk! Looking forward to it.

**Comment by nishantjainuk** [comment]
@mldrs 

I am working on the next version of this visual and have implemented this feature? Would you like to test it for me before I submit it to Microsoft. I hope you can point our any issue or suggest enhancement to make it better. 

Let me know and I can send you a copy of the visual that you can load offline in your report to test. 

Thanks
Nishant

**Comment by nishantjainuk** [comment]
@mldrs You can download the latest version to test [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/certification/Beta%20Version/SimpleWaterfall_dev.2.0.10.2.pbiviz)

**Comment by nishantjainuk** [comment]
@mldrs This features was delivered in version 2.0.10.0
