### ISSUE TITLE
Not responsive in Microsoft Teams PowerBI tab

### ISSUE THREAD

**Issue by algeeh** [nishantjainuk/SimpleWaterfall-PowerBI#30]
When viewing the waterfall inside Microsoft Teams using the PowerBI tab, it behaves weirdly and doesn't show the order correctly. 

When I have selected sort by ascending variance, it shows the final value in the middle rather than at the end. However, in the browser, it works perfectly.

**Comment by nishantjainuk** [comment]
@algeeh 

Thanks for the feedback. As the visual is working fine in browser but not in teams, I believe this is an issue with how Teams renders the report. Please raise this as a bug with the [Power BI Support](https://powerbi.microsoft.com/en-us/support/) or the [Power BI community](https://community.powerbi.com/)

Thanks
Nishant
