### ISSUE TITLE
Does not support DIN font

### ISSUE THREAD

**Issue by algeeh** [nishantjainuk/SimpleWaterfall-PowerBI#31]
The waterfall does not show DIN font as one of its options despite every other PowerBI visual supporting DIN font.

**Comment by nishantjainuk** [comment]
@algeeh 

Thanks for point this out. I am working on the next version of this visual and have implemented this feature? Would you like to test it for me before I submit it to Microsoft.

Let me know and I can send you a copy of the visual that you can load offline in your report to test. 

Thanks
Nishant

**Comment by nishantjainuk** [comment]
@algeeh You can download the latest version to test [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/blob/certification/Beta%20Version/SimpleWaterfall_dev.2.0.10.2.pbiviz)

**Comment by nishantjainuk** [comment]
@algeeh This was fixed in version 2.0.10.2 (current version)
