### ISSUE TITLE
Sorting Categories by Order opposed to just Cat?

### ISSUE THREAD

**Issue by DoubleuALT** [nishantjainuk/SimpleWaterfall-PowerBI#35]
Hello, First, love the tool! I have the following categories below that I want to sort the order of the categories by; however, when I use a second numerical variable to sort by it takes away my ability to Define Pillars. So, I either lose that function or have to do the following to order the categories the way I want.

![image](https://user-images.githubusercontent.com/44101407/91991275-b1faad80-ed00-11ea-9080-a84bcc4518c2.png)

**Comment by nishantjainuk** [comment]
@DoubleuALT 

Can you elaborate with more examples? I am not sure if I follow your issue. Also can you include the screenshot of your categories and / or measures you are using 

The visual has 3 basis sorting options:

1. Default - this is the sorting as defined by your model
2. Ascending -this overwrites the Power BI sorting and implements a custom sort in ascending value
3. Descending -this overwrites the Power BI sorting and implements a custom sort in descending value

Looking forward to your response

Thanks
Nishant

**Comment by DoubleuALT** [comment]
I figure this out, my mistake.
