### ISSUE TITLE
Customised Sentiment fail

### ISSUE THREAD

**Issue by carljohnanthony** [nishantjainuk/SimpleWaterfall-PowerBI#4]
Hi I just downloaed the add on and I love it.
I noticed you can personalise the each bars if you want to and anchor to zero if you choose too.

but when i reopened Power Bi it failed. the features arent there!!

**Comment by nishantjainuk** [comment]
Did you download it from the marketplace?

**Comment by carljohnanthony** [comment]
Yes

**Comment by carljohnanthony** [comment]
The behavior is a little unusual - I did not see these features before, and was delighted, but when i reopened it - it was all gone!

**Comment by nishantjainuk** [comment]
It takes about 2 weeks for the visual to go live on the market place. If you can't wait until then, happy to send you the beta version of the visual

Thanks
Nishant


On 29 Nov 2019 at 08:23, carljohnanthony <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes

**Comment by carljohnanthony** [comment]
That would be great! Really Appreciate this. I have spent alot of time
finding the right solution, and your version was perfect

**Comment by nishantjainuk** [comment]
Sure

I have attached the dev version of it, in case you want to use it now. Make sure you delete it and use the version from the marketplace when it goes live.

Would appreciate if you could leave some feedback on marketplace.

Thanks
Nishant


On 29 Nov 2019 at 08:43, carljohnanthony <notifications@github.com<mailto:notifications@github.com>> wrote:

That would be great! Really Appreciate this. I have spent alot of time
finding the right solution, and your version was perfect

**Comment by carljohnanthony** [comment]
Thank you. Where do i find the attachment? :)

**Comment by nishantjainuk** [comment]
Sorry

Seems the attachment didn't go through.

You can download it from here

https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/SimpleWaterfall_dev.2.0.3.pbiviz


Let me know if you are still missing the pillars section

Thanks
Nishant


On 29 Nov 2019 at 09:07, carljohnanthony <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you. Where do i find the attachment? :)

**Comment by carljohnanthony** [comment]
Hi Nishant,

Good News, and Weird News. Firstly, the good news. the beta version
installed correctly. Weird News - Before I installed it - I noticed the
Pillar section was back!

Sharing some feedback if you wanted to enhance some of the features of the
simple waterfall

   - Firstly, I noticed the Y Axis seemed to expand down. I should not need
   to go into negative territory, and was looking for a range feature. But in
   event, it exposed that I had a calculation error, bringing me slightly into
   the negative. In any event - Range would be good
   - Second, I would like to display my numbers in Absolute. With the
   waterfall, I need to Show target as a positive, and Actual as a negative..
   but it's not a negative.
   - Third, I would like to have a horizontal line that relates the pillars
   together, with automatic logic. Eg: Shipped + Backlog = In the Bag


I'm sharing my view, but please don't publish.

Finally - I'd like to buy you a bottle of wine, or something nice - please
send me your paypal, so I you treat yourself.

[image: image.png]

**Comment by nishantjainuk** [comment]
@carljohnanthony 

I have add a lot of new features to the latest version of this waterfall. Before I submit this to Microsoft, I would appreciate if you could test it and let me know if you are still missing any functionality. 

You can download the beta version [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true)

You can read about the new functionalities [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Version%20History.md#204)

Thanks

**Comment by carljohnanthony** [comment]
Hi Nishant

I am on a long weekend but will get back to you on Wednesday . Very
exciting !

**Comment by carljohnanthony** [comment]
Hi Nishantjainuk/Simplewaterfallpbi

Here is my feedback

**Comment by carljohnanthony** [comment]
Hi Nishantjainuk/Simplewaterfallpbi

Here is my feedback:

I have three defined pillars on, and the rest off. The on defined pillars
are placed correctly, but next to an off pillar causes an issue. The off
pillar is not placed correctly, and does not relate to the previous pillar.

I would like to see an option to display a positive value as a negative
pillar display.

Thanks Carl

**Comment by nishantjainuk** [comment]
Thanks Carl

Would it be possible to share a screenshot of the error in the visual. 

I will add the option

**Comment by carljohnanthony** [comment]
Vertical and horizontal side by size.

**Comment by nishantjainuk** [comment]
@carljohnanthony These features are now live in the latest version 2.10.0.1
