### ISSUE TITLE
Export Functionality

### ISSUE THREAD

**Issue by AliCot** [nishantjainuk/SimpleWaterfall-PowerBI#7]
Hi!

Thanks for the waterfall chart, it is really easy to use and very useful!
Is it possible to add the export functionality to it? Whenever I export to ppt or pdf, the waterfall is the only visual that doesn't display on my report, unfortunately. 

Thanks!

**Comment by nishantjainuk** [comment]
There is separate requirements from Microsoft for custom visuals to allow export to ppt or pdf. This is only my list of things to do. I will keep you posted as this comes along

Thanks!

**Comment by AliCot** [comment]
Great! thanks!

**Comment by nishantjainuk** [comment]
@AliCot I am now ready to submit the option for Microsoft to enable the export functionality on the visual. I can't confirm the timelines as I have never done this before. 

Before I request this option from Microsoft, I would appreciate if you could test the latest version for bugs. You can download it from [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true)

I will submit this to Microsoft next week

Thanks

**Comment by nishantjainuk** [comment]
@AliCot 

I have now submitted the visual to microsoft which can taken upto 3 weeks to show up on marketplace. Once that is done, I have to submit another request to microsoft to enable the export features. I don't know the timelines for this as I haven't don this before. Hopefully, it won't be long now. I will keep you posted on the progress.

**Comment by AliCot** [comment]
Fantastic! Thank you for keeping me updated!

**Comment by nishantjainuk** [comment]
@AliCot Good news. The visual is now certified.
