### ISSUE TITLE
Cannot recolor the bars in latest version 10.3

### ISSUE THREAD

**Issue by AdyB1** [nishantjainuk/SimpleWaterfall-PowerBI#74]
Hi,
Myself and a colleague have been using your waterfall for a few weeks and we have found that the latest version; 2.0.10.3 no longer gives you the option to recolor the bars, even with sentiment switched off. Version 2.0.10.2 does allow you to do this.
![v10 3](https://user-images.githubusercontent.com/95864242/145408160-cf50623a-7eb4-479e-bfe9-264ec784f9e8.png)

Cheers,
AdyB1

**Comment by nishantjainuk** [comment]
@AdyB1 

Please see my comment [here](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/issues/75#issuecomment-991867927) about this issue

**Comment by nishantjainuk** [comment]
@AdyB1

This issue should be resolved now with version 2.0.10.4. Can you please check and confirm?
