### ISSUE TITLE
Customized Labeling

### ISSUE THREAD

**Issue by NomiBash** [nishantjainuk/SimpleWaterfall-PowerBI#8]
I hope you are doing good.
 
I came across a situation where I need to show custom label for each pillar defined in simple waterfall.
 
Like we have conditional formatting for label colors can we have custom unit selection (e.g thousand,million,billion) for each pillar separately.
 
Currently some show in Thousand and some in Million, for my report I need to show all in Thousand.
![Simple WaterFAll](https://user-images.githubusercontent.com/60877696/74143645-3a521d80-4c0c-11ea-964b-d786c85ec256.JPG)

**Comment by nishantjainuk** [comment]
@NomiBash 

I have added this feature to the latest version of Simple Waterfall. Before I submit this to Microsoft, I would appreciate if you could test it

You can download it from [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true)

You can read about the new features [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Version%20History.md#204)

Thanks

**Comment by nishantjainuk** [comment]
@NomiBash 

I have add a new options for label formatting. Unfortunately, the standard conditional formatting option is not available for custom visuals, so can't add that yet (hopefully Microsoft will make it available soon :-)). 

In the mean time, I have added the options for you to select a default from thousands, millions and billions. 
 
![image](https://user-images.githubusercontent.com/24504997/75113203-a9d00000-5643-11ea-9596-841c568dfb3c.png)

I have submitted the visual to Microsoft and it can upto 3 weeks for the changes to reflect in the appsource. Until then, you can download the beta version [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true).

You can load this beta version and try it.

Note that you will have to remove the beta version and use the appsource version once it is live.

Looking forward for your feedback

**Comment by nishantjainuk** [comment]
@NomiBash These features are now available in the latest version 2.10.0.1
