### ISSUE TITLE
Selection of the categories (in x-axis) to filter other visuals - Not working

### ISSUE THREAD

**Issue by VatsalStoic** [nishantjainuk/SimpleWaterfall-PowerBI#80]
This issue is seen in latest Power BI versions. Initially it was working perfectly fine.

Clicking on a particular category (in x-axis) to filter out/interact with other 'simple waterfall' or other default visuals is not working either in PBI Desktop or PBI service (i.e. after publishing). It used to work fine with earlier versions  of PBI (and is still working in old PBI desktop version but not in published versions).

Please help resolve it at the earliest.

**Comment by nishantjainuk** [comment]
@VatsalStoic 

Please see my comment [here ](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/issues/75#issuecomment-991867927) about this issue

Thanks

**Comment by VatsalStoic** [comment]
Thank you for the response. Appreciate it.
