### ISSUE TITLE
max steps option disappeared

### ISSUE THREAD

**Issue by RamonGO** [nishantjainuk/SimpleWaterfall-PowerBI#85]
since last update (2.0.10.4) the option to set a max number of steps disappeared

**Comment by nishantjainuk** [comment]
The version 2.0.10.4 is still rolling out. Can you explain in more detail what you mean by the option as disappeared. Can you add few screenshots please

**Comment by RamonGO** [comment]
Here should be the limit steps toggle 
![image](https://user-images.githubusercontent.com/45214881/151144352-170295ce-496a-44f4-9fae-dac4a76b7bd4.png)

**Comment by nishantjainuk** [comment]
@RamonGO , is there any different between the 2 visuals that you have on your report i.e., different measures etc?

I shouldn't happen but can I ask you to recreate the visual that is not working and check if that helps

**Comment by RamonGO** [comment]
I just discovered that it is because of the drilldown option...

![image](https://user-images.githubusercontent.com/45214881/151155414-537aa576-d719-450f-b858-30c92ee133d3.png)

If I use the drilldown option to see the two levels the limit step toggle disappear. It could make sense

Many thanks

**Comment by nishantjainuk** [comment]
User error no bug tofix
