### ISSUE TITLE
Set Start Value for Y Axis

### ISSUE THREAD

**Issue by laky27** [nishantjainuk/SimpleWaterfall-PowerBI#9]
Hi there, 

Is there a way to set the start value for the Y Axis, for example in this waterfall it starts at 196M automatically, making the waterfall drop look more drastic than if the Y Axis started at 0 or say 100M
![image](https://user-images.githubusercontent.com/61324675/75050658-055a8c00-5492-11ea-95f1-5d486b84b3e7.png)

Thanks for the visual, love it!

**Comment by nishantjainuk** [comment]
Agreed. I will add this as an option in the next version. I will keep you posted on the progress 

Thanks

**Comment by nishantjainuk** [comment]
@laky27 

I have added a new option as per your suggestion. Now you can select whether you want the Y-axis to be determined automatically, always start from zero or provide a range. 

You will find the option in the "Y-axis" section of the properties pane

![image](https://user-images.githubusercontent.com/24504997/75113167-3b8b3d80-5643-11ea-8ccb-f11001e4824a.png)

I have submitted the visual to Microsoft and it can upto 3 weeks for the changes to reflect in the appsource. Until then, you can download the beta version [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true). 

You can load this beta version and try it. 

Note that you will have to remove the beta version and use the appsource version once it is live.  

Looking forward for your feedback

**Comment by Ohyinyin** [comment]
Hi there!! I was wondering if this fix is live in Microsoft yet? I still couldn't set base starting point from 0. Thanks in advance.

**Comment by nishantjainuk** [comment]
yes it was been approved 14th may and takes about 2 weeks to go live. If you look in the [appsource](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200000195?tab=Overview),  you can see the latest version to be 2.1.10.1. But when you try to install it, it will still come out as 2.0.3. It can be live anytime this week now.

**Comment by nishantjainuk** [comment]
@Ohyinyin @laky27 All these features are now available in the latest version 2.10.0.1.
